spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/tsarit?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pushpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nnikhiln2002@gmail.com
spring.mail.password=mlnzmcgbojvvcmks
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# JWT Configuration
tsarit.app.jwtSecret=SecretKeyMustBeLongEnoughToSecureTheApplicationAtLeast256BitsAttributesAreRequired
tsarit.app.jwtExpirationMs=86400000



# Razorpay Configuration
razorpay.api.key=rzp_live_Rz8vO7gI0lkWTk
razorpay.api.secret=eoF7UrrVeVZD3JTSzd9k5KD5

# Logging Configuration
logging.file.name=backend.log
logging.level.root=INFO
logging.level.com.tsarit=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# --- CORS & Frontend ---
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
app.frontend.url=http://localhost:5173
