spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/tsarit?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pushpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nnikhiln2002@gmail.com
spring.mail.password=ocjztpjkkowekjsn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# JWT Configuration
tsarit.app.jwtSecret=SecretKeyMustBeLongEnoughToSecureTheApplicationAtLeast256BitsAttributesAreRequired
tsarit.app.jwtExpirationMs=86400000
